pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'moud'

include 'core'
include 'net'
include 'client-launcher'
include 'server-minestom'
include 'server-supervisor'
include 'client-fabric'

def editorClientDir = file("editor-client")
if (editorClientDir.exists()) {
    include 'editor-client'
}
