plugins {
    id 'application'
    id 'com.gradleup.shadow' version '8.3.0'
}

dependencies {
    implementation project(':core')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'com.moud.supervisor.ServerSupervisor'
}

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar).configure {
    archiveClassifier.set('')
    mergeServiceFiles()
    manifest {
        attributes('Main-Class': application.mainClass.get())
    }
}
